### ISSUE TITLE
optimization: IterableSelector.getSize should not throw exception

### ISSUE THREAD

**Issue by noguespi** [TimefoldAI/timefold-solver#1125]
When enabling some kind for of moves (for example PillarMove with subpillars) implementations of IterableSelector.getSize will frequently throw an UnsupportedOperation exception or IllegalArgumentException. (example: [DefaultPillarSelector](https://github.com/TimefoldAI/timefold-solver/blob/9ec757a631fc6255349dc03f87673f97a5c49328/core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/entity/pillar/DefaultPillarSelector.java#L135), [PillarChangeMoveSelector](https://github.com/TimefoldAI/timefold-solver/blob/main/core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/generic/PillarChangeMoveSelector.java#L53), [SelectedCountLimitValueSelector](https://github.com/TimefoldAI/timefold-solver/blob/main/core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/value/decorator/SelectedCountLimitValueSelector.java#L29) )

Why I think the exception should be removed:

- Not exceptional: The [interface states that some selector may not have size](https://github.com/TimefoldAI/timefold-solver/blob/main/core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/IterableSelector.java#L19), it doesn't seems to be a good candidate for a runtime exception.

- Performance: Performance may not be a good argument against using exception but in this case the throwing method is called thousand times per second. It may have a negative performance impact to build a stacktrace everytime it's called.

- Log and telemetry pollution: the stacktrace is [logged everytime when trace is enabled](https://github.com/TimefoldAI/timefold-solver/blob/main/core/src/main/java/ai/timefold/solver/core/impl/heuristic/selector/move/decorator/FilteringMoveSelector.java#L108), providing little information and making logs hard to read. It may also be logged systemtically on app having telemetry/APM enabled because it is a runtime exception (of course, the offending class can be disabled in logging/telemetry configuration).

Maybe IterableSelector.getSize could return a `SelectorSize` interface which could be a `DefinedSelectorSize` or `UndefinedSelectorSize` which would force the caller to check wheter the size is defined or not.

IterableSelector.getSize could return -1 in case of no size, better performances but it would not make obvious the caller has to check the size != -1.

**Comment by triceo** [comment]
Hello @noguespi! Thanks for reporting.

Unfortunately, we will not be doing this, and I believe I owe you an explanation. 

The move selector framework is one of the oldest parts of the solver - by now it's existed for over a decade. It has been stretched far too much, and can no longer support everything we want to do with it. For that reason, we are now working on a brand new API to define moves - one that will better reflect the capabilities of Java in 2024, and how the programming model of the language has evolved.

For that reason, we will no longer be making any feature improvements to the old framework. Instead, we will focus our resources on bringing the new one as soon as possible. This will still take several months, because it means rewriting a core component of the solver from scratch, but we believe the end results will be well worth it.

Side note: the move selector framework is not public API. It was never meant to be - but considering that it was and still is the only way of writing custom moves for the solver, it evolved into something which is unfortunately widely used. The new API will be fully inside the public API, and with that come perks - it will be fully supported, fully backwards compatible, and it won't require so much boilerplate. Stay tuned.
