### ISSUE TITLE
Unfairness calculation returning wrong value

### ISSUE THREAD

**Issue by JelleVE** [TimefoldAI/timefold-solver#1187]
**Describe the bug**
I am trying to implement a load balancing with unfairness constraint. The calculated score, however, does not seem to resemble the value I expect when using the formula in this [blog post](https://timefold.ai/blog/load-balancing-and-fairness).

**Expected behavior**
Given the output of `loads()` on the load balancer, I calculate the expected value manually. Given these values:
```
198.79994718224827=1, 200.68255493240204=1, 304.48221618517016=1, 240.5584818825474=1
```
I would expect the value for unfairness to be `85.68367`

**Actual behavior**
The returned value is `0`.

**To Reproduce**
Sorry for the ugly printing code in the lambda function.

```
def balance_travel_distance(factory: ConstraintFactory):
    return (factory.for_each(TF_Expert)
            .group_by(ConstraintCollectors.load_balance(lambda expert: expert.calculate_total_driving_distance()/1000))
            .penalize_decimal(score_types[score_type_per_constraint[BALANCE_TRAVEL_DISTANCE]],
                lambda load_balance: [print(f'testing {load_balance.loads()}'), print(load_balance.unfairness()), load_balance.unfairness()][2])
            .as_constraint(BALANCE_TRAVEL_DISTANCE)
            )
```

## Environment

**Timefold Solver Version or Git ref**: 
1.15.0b0 (Python 3.11.10)

**Output of `java -version`:**
openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)

**Output of `uname -a` or `ver`:**
Linux host 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Christopher-Chianelli** [comment]
The right side are the counts that are used for load balancing; the left side are the items being load balanced. So for the given output in `loads()`:

`198.79994718224827=1, 200.68255493240204=1, 304.48221618517016=1, 240.5584818825474=1`

It is perfectly load balanced (and has an unfairness of 0): each distance is used exactly once. This is because you used the one-argument variant of `load_balance`, where the lambda represent what items to load balance.
You want to use the two argument version of `load_balance` instead (where the first argument are the items to balance, and the second argument is the weighting):

```python
def balance_travel_distance(factory: ConstraintFactory):
    return (factory.for_each(TF_Expert)
            .group_by(ConstraintCollectors.load_balance(
                      lambda expert: expert,
                      lambda expert: expert.calculate_total_driving_distance()//1000  # Note: this will be cast to int
            ))
            .penalize_decimal(score_types[score_type_per_constraint[BALANCE_TRAVEL_DISTANCE]],
                lambda load_balance: [print(f'testing {load_balance.loads()}'), print(load_balance.unfairness()), load_balance.unfairness()][2])
            .as_constraint(BALANCE_TRAVEL_DISTANCE)
            )
```

And would had this as the loads:

``Expert1=198, Expert2=200, Expert3=304, Expert4=240``

**Comment by JelleVE** [comment]
Perfect, thank you very much for the help. I'll close the issue.
