### ISSUE TITLE
On the GitHub Timefold-solver page, replace mvn clean install by mvn verify

### ISSUE THREAD

**Issue by Jdmbs** [TimefoldAI/timefold-solver#22]
On the GitHub Timefold-solver page there's mentioning of mvn clean install, whereas mvn verify is likely the better option.

How it is mentioned now:
_🚀 build-fast: mvn clean install -Dquickly skips any checks and code analysis (~1 min)
🔨 build-normally: mvn clean install runs tests, checks code style, skips documentation (~17 min)_

**Comment by triceo** [comment]
Thank you for taking the time to file the issue, @Jdmbs!

I thought about it and I think that the way it is currently done is correct - we assume the user wants to build the `SNAPSHOT` to have the artifacts installed, so that they can use them in their own use case locally. The alternative where the user just wants to build the sources and not do anything with them seems less likely to me, and the difference is (in my opinion) not big enough to introduce this granularity. 

(I'd even go as far as to say that if the user cares about the difference between `verify` and `install`, they will know to replace one with the other if that's what they want. This doesn't apply vice versa though, where the user might not know enough to understand there is a thing such as `install`.)

I am closing this issue. If you disagree with what I say, please provide rationale for why you think `verify` is better; we can discuss and reopen.
