### ISSUE TITLE
Best solution event is missing after ConstructionHeuristic with overconstrained planning

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#25]
Regression since OptaPlanner 8.36.0.Final
Caused by: https://issues.redhat.com/browse/PLANNER-1538 (an issue created in 2019 and fixed in 2023)

**Comment by ge0ffrey** [comment]
Backported fix (but not tests) to 0.8.x

**Comment by triceo** [comment]
@aioobe The goal of this issue was not to call events _during_ CH, but _after_ CH finishes. (For reasons stated in issue description.) Firing best solution events during CH doesn't make much sense, in my opinion, because those solutions are not initialized and therefore pretty much useless. 

The code you suggested does technically work, but practically is dangerous. The working solution is not cloned, and therefore the next step will modify it. This is the difference between working solution and best solution - best solution is a deep clone which the solver will not touch any more. The process of cloning a solution is expensive, and therefore we avoid it as much as we can.

**Comment by aioobe** [comment]
Ok. Thanks for the clarification. I understand the reasoning, and I agree with it apart from the case where all planning variables have `allowsUnassigned=true`. I've gone back and forth whether it makes sense for a CH phase in such situation for a long time now (you even [guided me](https://stackoverflow.com/q/69539641) in this matter ~3 years ago). I might go for a custom phase here. Thanks again, truly appreciate the help you provide and the hard work you put into Timefold. :pray:
