### ISSUE TITLE
Faster UnionMoveSelector by avoiding the JDK cache issue

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-solver#608]
This is a great video on the JDK instanceof issue:
  https://www.youtube.com/watch?v=-42brrfK9ww

Timefold doesn't use Drools any more, so most of the JDK issue described there doesn't affect us, except for this code in the UnionMoveSelector etc:
  https://github.com/lucamolteni/optaplanner/commit/5a76b2c400c5abf0ca0412554de2cc25c87de72b

Usually the score calculation makes  the performance of the UnionMoveSelector irrelevant, but in some simple cases with 1 constraint (TSP etc), the UnionMoveSelector shows up as 10-20% in a flamegraph, which is uncanny. The fix above probably fixes that.

**Comment by triceo** [comment]
I ran the type pollution agent across the entire codebase, by running *SmokeTest in the examples package. Attached is the full report. I'll start knocking these things off one after another.
[Type Check Statistics.txt](https://github.com/TimefoldAI/timefold-solver/files/14136986/Type.Check.Statistics.txt)

**Comment by triceo** [comment]
A thorough investigation uncovered many instances of type pollution, but after fixing them, no significant performance improvements. Therefore - since the code to fix this issue is fundamentally worse than the existing code - I decided not to merge the changes.

The working theory for why the type pollution is not a big problem for us is that it doesn't happen on the hot path. If we spend 90 % of time inside CS, improving the remaining 10 % will always bring marginal benefits.
