### ISSUE TITLE
Feat: Add a way to test @ConstraintConfiguration with ConstraintVerifier

### ISSUE THREAD

**Issue by Christopher-Chianelli** [TimefoldAI/timefold-solver#715]
**Is your feature request related to a problem? Please describe.**
When I define a `Constraint` using `penalizeConfigurable`:

```java
Constraint contentConflict(ConstraintFactory factory) {
    return factory.forEachUniquePair(Talk.class,
        overlapping(t -> t.getTimeslot().getStartDateTime(),
            t -> t.getTimeslot().getEndDateTime()),
        filtering((talk1, talk2) -> talk1.overlappingContentCount(talk2) > 0))
        .penalizeConfigurable("Content conflict",
                (talk1, talk2) -> talk1.overlappingContentCount(talk2)
                        * talk1.overlappingDurationInMinutes(talk2));
}
```

I want to be able to test if the `contentConflict` field in my `@ConstraintConfiguration` class corresponds with the `contentConflict` constraint using a `ConstraintVerifier` test.

**Describe the solution you'd like**

An API that takes the `@ConstraintConfiguration` class and check the score of a single constraint:

```java
@Test
void configuredContentConflict() {
    constraintVerifier.verifyThat(MyConstraintProvider::contentConflict)
                .configuredWith(new MyConstraintConfiguration().withContentConflictWeight(HardSoftScore.ofHard(1)))
                .given(talk1, talk2)
                .scores(HardSoftScore.ofHard(4));
}
```

**Additional context**
https://stackoverflow.com/questions/78136960/how-to-write-unit-tests-for-constraints-where-it-is-applied-penalizeconfigurable

**Comment by triceo** [comment]
`ConstraintConfiguration` becomes deprecated with this:
https://github.com/TimefoldAI/timefold-solver/issues/924

But the issue still stands even for the new API, `ConstraintWeightOverrides`.

**Comment by triceo** [comment]
On further analysis:

- Adding constraint configuration to `SingleConstraintVerification` doesn't make sense to me. That would in effect be testing the fact that, given numbers A and B, the result is `A × B`. This is so basic that I do not think we should support this case.
- This leaves the case of `MultiConstraintVerification`, where the user passes an entire solution and checks for the total score. Here, weight overrides make sense and because they are part of the solution, they will be taken into account automatically.

With that, I'll close this issue when the referenced PR is merged, because it brings all the required functionality.
