### ISSUE TITLE
List variable model fails to recompute first list element in SolutionManager.explain()

### ISSUE THREAD

**Issue by holgerbrandl** [TimefoldAI/timefold-solver#857]
**Describe the bug**
When using `SolutionManager.explain()` to recompute all shadow variables in a list-variable model, it fails to update the first list element.

**Expected behavior**
Consider the following gist https://gist.github.com/holgerbrandl/f3cc4c96477b14d0c165f90933715cef

Results is
```
[
C1::com.systema.experiments.Room@4b45a2f5(null-null), 
C2::com.systema.experiments.Room@4b45a2f5(2024-01-01T00:00:00Z-2024-01-02T00:00:00Z), 
C3::com.systema.experiments.Room@4b45a2f5(2024-01-02T00:00:00Z-2024-01-03T00:00:00Z)
]
```

The first course is not recomputed, that is the variable listener is not run for it.

**Actual behavior**
Also `C1` should have start and end date and not `null-null`

## Environment

v1.10
java 17

## Additional information
This partially relates to https://github.com/TimefoldAI/timefold-solver/issues/823 because without a selection-filter during construction, one must build a custom construction which typically relies on a properly functioning `explain` to update the shadow-variables during construction.

FYI @terbrack

**Comment by triceo** [comment]
Hello @holgerbrandl, thanks for reporting!

Did you consider using `SolutionManager.update(...)`? That is actually _designed_ to update shadow variables, as opposed to `explain()`, where it is a side-effect. If the same problem exists there, and I have a suspicion that it will, I'm placing this in my backlog and will investigate when time permits.

**Comment by holgerbrandl** [comment]
I've rerun the provided example with `SolutionManager.update(...)` but the problem remains: the first planning entity's shadow variables are not updated.

**Comment by triceo** [comment]
Thank you, @holgerbrandl!

**Comment by terbrack** [comment]
Hello @triceo, can you estimate when this bug will be fixed?
Since it is obviously a blocker in migrating to a list variable api, we are really looking forward to that fix.
Best,
Hajo

**Comment by zepfred** [comment]
Hey @holgerbrandl @terbrack. I've been investigating the issue, and it doesn't look like a bug.

`CourseVariablesListener` updates the `start` and `end` values from `Course`. Because it is bound to `prevCourse`, only values from C2 and C3 are changed during the listeners' life cycle. Since the value of `prevCourse` is not updated for `C1`, it is "skipped" from being analyzed by `CourseVariablesListener`.

One possible solution is to adjust the configuration of the shadow variable and bind it to the `room` instead. This way, all three courses will be caught by `CourseVariablesListener`. 

```
    @ShadowVariable(
        variableListenerClass = CourseVariablesListener::class,
        sourceVariableName = "room"
    )
    var start: Instant? = null
```

Additionally, you can enhance the listener to avoid recalculating dates unnecessarily. See an example here: https://github.com/TimefoldAI/timefold-quickstarts/blob/b2056965eb304283eba72b4fd6e887bce48c50d9/java/vehicle-routing/src/main/java/org/acme/vehiclerouting/solver/ArrivalTimeUpdatingVariableListener.java#L38

**Comment by triceo** [comment]
We haven't heard back in a while. Considering that we have an explanation for the behavior, I am closing this issue. If the issue still persist, please reopen.

**Comment by holgerbrandl** [comment]
Thanks for the kind reply @zepfred & @triceo and sry for my late response. Indeed, adjusting the shadow variable to "room" solves the problem.
